//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryFashionHousesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothesInShop
    {
        public int CLSH_ID { get; set; }
        public int CLSH_SH { get; set; }
        public int CLSH_CL { get; set; }
        public int CLSH_QTY { get; set; }
        public float CLSH_COST { get; set; }
    
        public virtual Clothes Clothes { get; set; }
        public virtual ShopClothes ShopClothes { get; set; }
    }
}
