//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryFashionHousesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clothes()
        {
            this.ClothesInShop = new HashSet<ClothesInShop>();
        }
    
        public int CL_ID { get; set; }
        public int CL_FH { get; set; }
        public int CL_DES { get; set; }
        public string CL_DESCRIPTION { get; set; }
        public string CL_CATEGORY { get; set; }
        public string CL_COLOR { get; set; }
    
        public virtual Designers Designers { get; set; }
        public virtual FashionHouses FashionHouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClothesInShop> ClothesInShop { get; set; }
    }
}
