//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryFashionHousesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Designers()
        {
            this.Clothes = new HashSet<Clothes>();
        }
    
        public int DES_ID { get; set; }
        public string DES_FULLNAME { get; set; }
        public int DES_PASSPORT { get; set; }
        public string DES_GENDER { get; set; }
        public int DES_FH { get; set; }
        public string DES_BIRTHDAY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clothes> Clothes { get; set; }
        public virtual FashionHouses FashionHouses { get; set; }
    }
}
