//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryFashionHousesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presidents
    {
        public int PR_ID { get; set; }
        public int PR_PASSPORT { get; set; }
        public int PR_FH { get; set; }
        public string PR_FULLNAME { get; set; }
    
        public virtual FashionHouses FashionHouses { get; set; }
    }
}
