//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryFashionHousesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopClothes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopClothes()
        {
            this.ClothesInShop = new HashSet<ClothesInShop>();
        }
    
        public int SH_ID { get; set; }
        public string SH_ADRESS { get; set; }
        public int SH_QTY_EMP { get; set; }
        public int SH_FH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClothesInShop> ClothesInShop { get; set; }
        public virtual FashionHouses FashionHouses { get; set; }
    }
}
